[config]
iterations = 500

[[cases]]
a = "1"
b = "1"
name = "1 << 1"

[[cases]]
a = "1"
b = "32"
name = "1 << 32"

[[cases]]
a = "1"
b = "64"
name = "1 << 64"

[[cases]]
a = "1"
b = "256"
name = "1 << 256"

[[cases]]
a = "1"
b = "1024"
name = "1 << 1024"

[[cases]]
a = "{9,50}"
b = "1"
name = "50-digit << 1"

[[cases]]
a = "{9,50}"
b = "32"
name = "50-digit << 32"

[[cases]]
a = "{9,50}"
b = "64"
name = "50-digit << 64"

[[cases]]
a = "{9,50}"
b = "128"
name = "50-digit << 128"

[[cases]]
a = "{9,100}"
b = "100"
name = "100-digit << 100"

[[cases]]
a = "{9,200}"
b = "256"
name = "200-digit << 256"

[[cases]]
a = "123456789012345678901234567890"
b = "500"
name = "30-digit << 500"

[[cases]]
a = "{9,1000}"
b = "1000"
name = "1000-digit << 1000"

[[cases]]
a = "{9,5000}"
b = "5000"
name = "5000-digit << 5000"

[[cases]]
a = "{9,10000}"
b = "10000"
name = "10000-digit << 10000"

[[cases]]
a = "1"
b = "100000"
name = "1 << 100000 (~30103 digits)"

[[cases]]
a = "{9,1000}"
b = "32768"
name = "1000-digit << 32768"
