[config]
iterations = 100

[[cases]]
a = "100"
b = "10"
name = "Simple division, no remainder"

[[cases]]
a = "10"
b = "3"
name = "Division with remainder"

[[cases]]
a = "7"
b = "2"
name = "Division of small numbers"

[[cases]]
a = "5"
b = "10"
name = "Division resulting in zero"

[[cases]]
a = "12345"
b = "1"
name = "Division by one"

[[cases]]
a = "-10"
b = "3"
name = "Negative dividend, positive divisor"

[[cases]]
a = "10"
b = "-3"
name = "Positive dividend, negative divisor"

[[cases]]
a = "-10"
b = "-3"
name = "Negative dividend, negative divisor"

[[cases]]
a = "0"
b = "5"
name = "Zero dividend"

[[cases]]
a = "9999999999"
b = "333"
name = "Large number division"

[[cases]]
a = "1{0,50}"
b = "7"
name = "Very large number division"

[[cases]]
a = "1{0,30}"
b = "1{0,10}"
name = "Division of large numbers with exact result"

[[cases]]
a = "12345"
b = "{9,20}"
name = "Division by large number"

[[cases]]
a = "6765"
b = "4181"
name = "Fibonacci number division"

[[cases]]
a = "2147483647"
b = "997"
name = "Prime number division"

[[cases]]
a = "9223372036854775807"
b = "2"
name = "Division near Int64 limit"

[[cases]]
a = "{12345,10}"
b = "{6789,12}"
name = "Division with around 50 digits divisor just below dividend"

[[cases]]
a = "1{0,20}"
b = "1{0,5}"
name = "Division with exact powers of 10"

[[cases]]
a = "{990132857498314692374162398217,10}"
b = "{85172390413429847239,10}"
name = "Division of repeated digits"

[[cases]]
a = "{9,100}"
b = "3"
name = "Extreme large dividend and small divisor"
