[config]
iterations = 100

[[cases]]
a = "1"
name = "Power of 10 (10^0)"

[[cases]]
a = "10"
name = "Power of 10 (10^1)"

[[cases]]
a = "100"
name = "Power of 10 (10^2)"

[[cases]]
a = "0.1"
name = "Power of 10 (10^-1)"

[[cases]]
a = "0.01"
name = "Power of 10 (10^-2)"

[[cases]]
a = "5"
name = "Between powers - middle"

[[cases]]
a = "2"
name = "Between powers - closer to lower"

[[cases]]
a = "9"
name = "Between powers - closer to upper"

[[cases]]
a = "3.1415926535897932384626433832795"
name = "Decimal with many digits"

[[cases]]
a = "0.0000001"
name = "Small number close to 0"

[[cases]]
a = "1000000000000"
name = "Large number"

[[cases]]
a = "1.00000001"
name = "Close to 1 (above)"

[[cases]]
a = "0.99999999"
name = "Close to 1 (below)"

[[cases]]
a = "31.62277660168"
name = "Non-integer power of 10 (10^1.5)"

[[cases]]
a = "1.234567890123456789"
name = "Repeating pattern"

[[cases]]
a = "2.718281828459045235360287471352662"
name = "Very precise input"

[[cases]]
a = "123456789012345678901234"
name = "Integer with many digits"

[[cases]]
a = "3.16227766017"
name = "Square root of 10"

[[cases]]
a = "299792458"
name = "Scientific calculation value"

[[cases]]
a = "4.2857142857"
name = "Random decimal value"
