[config]
iterations = 10000

[[cases]]
a = "10"
b = "3"
name = "Simple modulo with remainder"

[[cases]]
a = "10"
b = "5"
name = "Modulo with no remainder"

[[cases]]
a = "10.5"
b = "3.5"
name = "Decimal values (even division)"

[[cases]]
a = "10.75"
b = "2.5"
name = "Different decimal places"

[[cases]]
a = "3"
b = "10"
name = "Modulus > dividend"

[[cases]]
a = "-10"
b = "3"
name = "Negative dividend, positive divisor"

[[cases]]
a = "10"
b = "-3"
name = "Positive dividend, negative divisor"

[[cases]]
a = "-10"
b = "-3"
name = "Negative dividend, negative divisor"

[[cases]]
a = "-10.5"
b = "3.5"
name = "Decimal values, negative dividend"

[[cases]]
a = "-10.5"
b = "3"
name = "Decimal with remainder, negative dividend"

[[cases]]
a = "10"
b = "1"
name = "Modulo by 1"

[[cases]]
a = "0"
b = "5"
name = "Zero dividend"

[[cases]]
a = "10"
b = "0.3"
name = "Divisor < 1"

[[cases]]
a = "1000000007"
b = "13"
name = "Large number modulo"

[[cases]]
a = "0.0000023"
b = "0.0000007"
name = "Small number modulo"

[[cases]]
a = "7.5"
b = "7.5"
name = "Equal values"

[[cases]]
a = "3.14159265358979323846"
b = "1.5"
name = "High precision values"

[[cases]]
a = "9.999999"
b = "2"
name = "Values close to exact multiple"

[[cases]]
a = "12345678901234567890"
b = "9876543210"
name = "Large integers modulo"

[[cases]]
a = "1"
b = "3"
name = "Values generating repeating patterns"
