[config]
iterations = 100

[[cases]]
a = "9"
b = "2"
name = "Square root of perfect square"

[[cases]]
a = "2"
b = "2"
name = "Square root of non-perfect square"

[[cases]]
a = "8"
b = "3"
name = "Cube root of perfect cube"

[[cases]]
a = "10"
b = "3"
name = "Cube root of non-perfect cube"

[[cases]]
a = "16"
b = "4"
name = "Fourth root of perfect power"

[[cases]]
a = "32"
b = "5"
name = "Fifth root of perfect power"

[[cases]]
a = "0.25"
b = "2"
name = "Root of decimal < 1"

[[cases]]
a = "0.0625"
b = "4"
name = "Root of small decimal"

[[cases]]
a = "2.7182818284590452353602874"
b = "2"
name = "High precision decimal"

[[cases]]
a = "1000000"
b = "2"
name = "Large integer"

[[cases]]
a = "10"
b = "100"
name = "Large root"

[[cases]]
a = "-27"
b = "3"
name = "Odd root of negative number"

[[cases]]
a = "1"
b = "7"
name = "Root of 1 (any root)"

[[cases]]
a = "0"
b = "3"
name = "Root of 0"

[[cases]]
a = "123.456"
b = "2"
name = "Custom decimal"
