[config]
iterations = 10000

[[cases]]
a = "10"
b = "2"
name = "Integer division, no remainder"

[[cases]]
a = "10"
b = "3"
name = "Integer division, with remainder"

[[cases]]
a = "10.5"
b = "2.5"
name = "Decimal division"

[[cases]]
a = "5"
b = "2"
name = "Division resulting in integer"

[[cases]]
a = "10.75"
b = "1.5"
name = "Different decimal places"

[[cases]]
a = "-10"
b = "3"
name = "Negative dividend, positive divisor"

[[cases]]
a = "10"
b = "-3"
name = "Positive dividend, negative divisor"

[[cases]]
a = "-10"
b = "-3"
name = "Negative dividend, negative divisor"

[[cases]]
a = "-10.5"
b = "3.5"
name = "Decimal, negative dividend, positive divisor"

[[cases]]
a = "10"
b = "1"
name = "Division by 1"

[[cases]]
a = "0"
b = "5"
name = "Zero dividend"

[[cases]]
a = "10"
b = "0.5"
name = "Division by decimal < 1"

[[cases]]
a = "0"
b = "-5"
name = "Division resulting in zero"

[[cases]]
a = "1000000000"
b = "7"
name = "Large number division"

[[cases]]
a = "0.0000001"
b = "0.0000002"
name = "Small number division"

[[cases]]
a = "123456789012345"
b = "987654321"
name = "Large dividend and divisor"

[[cases]]
a = "3.14159265358979323846"
b = "1.5"
name = "High precision dividend"

[[cases]]
a = "1.0000001"
b = "1"
name = "Very close values"

[[cases]]
a = "10000"
b = "100"
name = "Power of 10 values"

[[cases]]
a = "9.9999999"
b = "2"
name = "Edge values"
